mutation CreateNewUser($displayName: String!, $email: String!) @auth(level: USER) {
  user_insert(data: {displayName: $displayName, email: $email, id_expr: "uuidV4()", createdAt_expr: "request.time"})
}

query GetCurrentUserMealPlans @auth(level: USER) {
  mealPlans(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    name
    startDate
    endDate
  }
}

mutation CreateNewMealPlan($name: String!, $startDate: Date!, $endDate: Date!) @auth(level: USER) {
  mealPlan_insert(data: {name: $name, startDate: $startDate, endDate: $endDate, userId_expr: "auth.uid", aiGenerated: false, createdAt_expr: "request.time"})
}

query ListAllTrainers @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  trainers {
    id
    displayName
    specialization
    photoUrl
  }
}