type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  age: Int
  gender: String
  height: Float
  weight: Float
  fitnessGoals: [String]
  dietaryPreferences: [String]
  activityLevel: String
}

type Trainer @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  certificationId: String!
  photoUrl: String
  specialization: String
  bio: String
}

type WorkoutPlan @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  startDate: Date!
  endDate: Date!
  aiGenerated: Boolean!
  trainerNotes: String
}

type Exercise @table {
  workoutPlan: WorkoutPlan!
  name: String!
  type: String!
  durationOrReps: String!
  sets: Int!
  weightRecommendation: Float
  videoUrl: String
  instructions: String
}

type MealPlan @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  startDate: Date!
  endDate: Date!
  aiGenerated: Boolean!
  trainerNotes: String
}

type Meal @table {
  mealPlan: MealPlan!
  name: String!
  type: String!
  calories: Int!
  protein: Float!
  carbs: Float!
  fat: Float!
  ingredients: [String]
  recipeInstructions: String
  imageUrl: String
}